spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fast_food
    password: root123
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    show-sql: true
  sql:
    init:
      mode: never
  jackson:
    serialization:
      fail-on-empty-beans: false
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
  eureka:
    instance:
      hostname: localhost
    client:
      fetch-registry: true
      register-with-eureka: true
app:
  stripe:
    secret-key: sk_test_51LN8s1E8H0vnYjdmBtMPCCP3MrEVfQpTjA2HXmA7arqmc6ICz0benXBOXHPtxSv5UKaorTHmbr8FKkmpEACPuLhB00jo7SDEh2

