spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fast_food
    password: root123
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: never
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true

